app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.114/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false&allowLoadLocalInfile=true&serverTimezone=GMT
    username: root
    password: NPN_loczzf2_root
  jdbc:
    template:
      fetch-size: 1000
  ## thymeleaf
  thymeleaf:
    cache: true

# currency api key from https://fixer.io
currency.api.appkey: 34edd354c807eb087180ed9205346e34
