app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false&allowLoadLocalInfile=true
    username: user
    password: pwd
  jdbc:
    template:
      fetch-size: 1000
  ## thymeleaf
  thymeleaf:
    cache: true

# currency api key from https://fixer.io
currency.api.appkey: REPLACE_YOUR_APPKEY

