app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.204:3306/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false&allowLoadLocalInfile=true
    username: diankou
    password: Diankou@!123
  ## thymeleaf
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
