app:
  env: prod
  cache-path: /data/om-dtask/cache

logging:
  config: classpath:log4j2-prod.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host/open_mediation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowLoadLocalInfile=true
    username: user
    password: pwd
