app:
  env: dev

logging:
  config: classpath:log4j2-dev.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false&allowLoadLocalInfile=true
    username: xxx
    password: xxxxx
  ## thymeleaf
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面

# currency api key from https://fixer.io
currency.apiKey: your_appKey
