app:
  env: prod

logging:
  config: classpath:log4j2-prod.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://host/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false&allowLoadLocalInfile=true
    username: user
    password: pwd
currency.api.appkey: your appKey