app:
  env: prod
  cache-path: /data/om-dtask/cache

logging:
  config: classpath:log4j2-prod.xml

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=false&allowLoadLocalInfile=true
    username: user
    password: passswd 
